### ISSUE TITLE
Add author names in documentations

### ISSUE THREAD

**Issue by RahulBhalley** [dl4s-team/dl4s-evolution#1]
@philipturner please add the author names in documentations and (possibly) use _we_ instead of _I_.

**Comment by philipturner** [comment]
I have been trying to avoid the use of "i", but I may have missed it. Could you point out a specific point where I did use the word?

All of the documentation on this web page was written by myself, so I'd rather wait until someone else made some documentation here before I say which author made it.

**Comment by RahulBhalley** [comment]
> I have been trying to avoid the use of "I", but I may have missed it. Could you point out a specific point where I did use the word?

**Comment by RahulBhalley** [comment]
@philipturner check the pull request #2.

**Comment by RahulBhalley** [comment]
I believe it's a good approach to make pull requests instead of directly committing to the repository. This way the owners of this repository will be able to approve the pull requests based on a collective decision.

**Comment by RahulBhalley** [comment]
@philipturner Could you please give me and @palle-k (and potentially others) a more deeper access to this organization? 

This way we all can collectively make decisions regarding the work done here by different means such as merging the pull requests (from one of us and potentially public (in future)), assign oneself or others for reviewing the pull requests, etc.

**Comment by philipturner** [comment]
I'll try to stop making commits to this repository until we have this sorted out. @palle-k and I already have ownership access. I'll try to give you the "Triage" access level right now, but let me know if you want more permissions.

Originally, I was the only person working on this repository. It was a place to publish some temporary plans for the Metal implementation, but it grew over time. I have already made initial progress on the rebuilding of DL4S, but my source code is currently in a personal private repository.

It makes sense that major changes (e.g. changing the organization's profile picture, adding a new documentation section) should warrant a group discussion. However, I would like to bypass the pull request process for minor edits (e.g. adding a new supported activation function) since I'm the primary contributor. What are your thoughts on this?

**Comment by RahulBhalley** [comment]
It's fine by me.
